export class Orderdetails {
    "orderId":string
    "bookId":string
    "sellerId":string
    "bookname":string
    "sellername":string
    "bookImage":string
    "category":string
    "publisher":string
    "author":string
    "userId":string
    "quantity":number
    "totalprice":number
    "name":string
    "address":string
    "orderdate":string
    "shippingdate":string
    "mobileno":string
    "price":number
    "orderstatus":string
}
